CREATE DATABASE IF NOT EXISTS zbt_tickets;
USE zbt_tickets;
DROP TABLE IF EXISTS Tickets;
CREATE TABLE Tickets (
  cid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(4) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE
);
